In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,5,37,7]], np.int64)

In [3]:
myarr[0,1]

np.int64(5)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 37,  7]])

In [8]:
myarr.size

4

In [9]:
myarr = np.array([3,5,37,7])

In [10]:
myarr.shape

(4,)

In [11]:
np.array({3,5,37,7})

array({5, 3, 37, 7}, dtype=object)

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.shape

(2, 5)

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1,10,4)

In [18]:
lspace

array([ 1.,  4.,  7., 10.])

In [19]:
emp = np.empty((4,6))

In [20]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [21]:
emp_like = np.empty_like(lspace)

In [22]:
emp_like

array([ 1.,  4.,  7., 10.])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
ide.shape

(45, 45)

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr = arr.reshape(3, 33)

In [29]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr = arr.ravel()

In [31]:
arr.shape

(99,)

In [32]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [33]:
ar = np.array(x)

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [35]:
ar.sum(axis = 0)

array([12,  8,  9])

In [36]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [37]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [38]:
ar.flat

In [39]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [40]:
ar.ndim

2

In [41]:
ar.size

9

In [42]:
ar.nbytes

72

In [43]:
one = np.array([1,3,4,654,2])

In [44]:
one.argmax()

np.int64(3)

In [45]:
one.argmin()

np.int64(0)

In [46]:
one.argsort()

array([0, 4, 1, 2, 3])

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.argmin()

np.int64(8)

In [49]:
ar.argmax()

np.int64(6)

In [50]:
ar.argmax(axis=0)

array([2, 1, 1])

In [51]:
ar.argmax(axis=1)

array([2, 2, 0])

In [52]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [53]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [54]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [57]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [58]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [59]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [60]:
ar.sum()

np.int64(29)

In [61]:
ar.max()

np.int64(7)

In [62]:
ar.min()

np.int64(0)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [65]:
np.count_nonzero(ar)

8

In [66]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [67]:
ar[1,2] = 0

In [68]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [69]:
import sys

In [70]:
py_ar = [0,4,55,2]

In [71]:
np_ar = np.array(py_ar)

In [72]:
sys.getsizeof(1) * len(py_ar)

112

In [73]:
np_ar.itemsize * np_ar.size

32